<a href="https://colab.research.google.com/github/kstyle2198/NLP_TIPS/blob/main/%ED%95%9C%EA%B8%80_%EB%AC%B8%EC%9E%A5%EC%9C%A0%EC%82%AC%EB%8F%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# KR-SBERT

https://github.com/snunlp/KR-SBERT

In [14]:
!pip install sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 2.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 14.8 MB/s eta 0:00:00
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=68fb2259af6e274098da5fd33e04460e388278cef00e290013bb059cf129404f
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence_transformers


In [ ]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('snunlp/KR-SBERT-V40K-klueNLI-augSTS')

.gitattributes:   0%|          | 0.00/1.23k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/4.02k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/467M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/967k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/394 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/336k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

In [14]:
# sentences = ['잠이 옵니다', '졸음이 옵니다', '기차가 옵니다']

sentences = ['아르곤 용접시 사전에 환기를 합니다.', '어제 아르곤 용접 폭발 사고가 났습니다.', '도장 작업시 주변 정리를 철저히 합니다.']

In [ ]:
vectors = model.encode(sentences) # encode sentences into vectors
similarities = util.cos_sim(vectors, vectors) # compute similarity between sentence vectors
similarities

tensor([[1.0000, 0.6002, 0.4756],
        [0.6002, 1.0000, 0.3247],
        [0.4756, 0.3247, 1.0000]])

# jhgan/ko-sroberta-multitask

https://huggingface.co/jhgan/ko-sroberta-multitask

In [12]:
import pandas as pd
from sentence_transformers import SentenceTransformer, util
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
# model = SentenceTransformer('jhgan/ko-sroberta-multitask')

model = SentenceTransformer('jhgan/ko-sroberta-multitask')

In [15]:
embeddings = model.encode(sentences)
embeddings

array([[-6.0790133e-01, -1.1869130e-01,  3.7624362e-01, ...,
         6.1215323e-01,  4.0965810e-01, -1.7261672e-01],
       [-4.4415951e-01, -6.0619837e-01,  4.6051046e-01, ...,
         9.6764817e-04,  4.6226609e-01, -2.5306019e-01],
       [ 2.0911913e-01,  1.9398771e-01, -2.6798275e-01, ...,
         1.1331683e+00,  6.3240355e-01, -2.9789791e-01]], dtype=float32)

In [16]:
similarities = util.cos_sim(embeddings, embeddings) # compute similarity between sentence vectors
similarities

tensor([[1.0000, 0.4298, 0.5489],
        [0.4298, 1.0000, 0.1119],
        [0.5489, 0.1119, 1.0000]])

# 양자화

In [1]:
!pip install -q -U bitsandbytes
!pip install -q -U git+https://github.com/huggingface/transformers.git
!pip install -q -U git+https://github.com/huggingface/peft.git
!pip install -q -U git+https://github.com/huggingface/accelerate.git

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


In [2]:
!pip install transformers

In [15]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig, AutoModel
from sentence_transformers import SentenceTransformer, util


bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

In [4]:
model_id = "jhgan/ko-sroberta-multitask"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModel.from_pretrained(model_id, quantization_config=bnb_config, device_map="auto")
model

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()


RobertaModel(
  (embeddings): RobertaEmbeddings(
    (word_embeddings): Embedding(32000, 768, padding_idx=1)
    (position_embeddings): Embedding(514, 768, padding_idx=1)
    (token_type_embeddings): Embedding(1, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): RobertaEncoder(
    (layer): ModuleList(
      (0-11): 12 x RobertaLayer(
        (attention): RobertaAttention(
          (self): RobertaSelfAttention(
            (query): Linear4bit(in_features=768, out_features=768, bias=True)
            (key): Linear4bit(in_features=768, out_features=768, bias=True)
            (value): Linear4bit(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): RobertaSelfOutput(
            (dense): Linear4bit(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
   

In [5]:
sentences = ['아르곤 용접시 사전에 환기를 합니다.', '어제 아르곤 용접 폭발 사고가 났습니다.', '도장 작업시 주변 정리를 철저히 합니다.']

In [7]:
encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')

In [8]:
# Compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input)

In [10]:
#Mean Pooling - Take attention mask into account for correct averaging
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)


In [12]:
embeddings = mean_pooling(model_output, encoded_input['attention_mask'])

In [16]:
similarities = util.cos_sim(embeddings, embeddings) # compute similarity between sentence vectors
similarities

tensor([[1.0000, 0.4490, 0.5521],
        [0.4490, 1.0000, 0.1091],
        [0.5521, 0.1091, 1.0000]])